config/routes.rb
Rails.application.routes.draw do

  root 'web#landing'

  scope 'api' do
    get 'version/:ver' => 'users#version'
	  resources :categories, only: [:create, :index]
	  
	  

	  resources :offers, only: [:index]
	  post 'add_fooditem_image' => 'food_items#add_image'
	  get 'get_users' => 'users#get_users'
	  get 'get_restaurants' => 'restaurants#send_all'
	  put 'user' => 'users#update'
	  patch 'user' => 'users#update'
	  scope "user" do
	    post 'signup' => 'users#create'
	    delete 'signout' => 'users#signout'
	    post 'restaurant/signup' => 'users#restaurant_user_create'
	    post 'signin' => 'users#signin'
	    get 'email/verify/:token' => 'users#verify_email'
	    get 'follow/:id' => 'users#follow'
	    get 'unfollow/:id' => 'users#unfollow'
	    get 'followers' => 'users#followers'
	    post 'reviews' => 'reviews#create_user_review'
	    get 'social/:id' => 'users#social'
	    post 'message/:id' => 'users#message'
	    get 'notifications' => 'users#notifications'
	    get 'all_notifications' => 'push_notification#notifications'
	    get 'notifications/seen' => 'users#notification_seen'
	    post ':type/:id' => 'users#report'
	    resources :posts , except: [:new, :edit , :show]
	    get 'like/:typee/:id' => 'users#likers'
	    get 'unlike/:typee/:id' => 'users#unlike'
	    get 'dislike/:typee/:id' => 'users#dislike' 
	    scope 'posts' do
	      get 'likes/:id' => 'posts#likeable'
	      post 'comment/new' => 'posts#comment'
	      get 'comments/:id' => 'posts#showcomment'
	      resources :checkins, only: [:update]
	    end
	    get 'referral/:referral_code' => 'referral#create'
	    get 'referral' => 'referral#get_users'
	    post 'claim_credit' => 'restaurants#claim_credit'
	    get 'newsfeed' => 'newsfeed#index'
	    get 'localfeed' => 'users#my_feeds'
	    get 'all_feed' => 'newsfeed#localfeed_updated'
	    get 'follows/check/:id' => 'users#chk_follow_user'
	    resources :khaba_history, only: [:index ]
	    get 'credits' => 'khaba_history#credit'

	    get 'bookmarks' => 'users#get_user_likes'

	    post 'eat_buddies' => 'search#find_fb_friends'
	    post 'gcm' => 'push_notification#set_key'
	    post 'profile_picture' => 'users#update_picture'
	    get 'post/:id' => 'posts#get_post'
	  end
	  resources :restaurants, except: [:new, :edit , :show]
	  post 'comment/reply/:id' => 'reply#reply_to_comment'
	  scope "restaurants" do
	    get 'explore' => 'restaurants#explore_rest'
	    post 'qrcode' => 'restaurants#qrcode'
	    get 'featured' => 'restaurants#featuredr'
	    get 'social/:id' => 'restaurants#social'
	    get 'follow/:id' => 'restaurants#follow'
	    get 'unfollow/:id' => 'restaurants#unfollow'
	    post 'reviews' => 'reviews#create_restaurant_review'
	    resources :menus, except: [:new, :edit]
	    scope 'menus' do
	      resources :food_items, except: [:new, :edit]
	    end
	    resources :rating, only: [:create]
	    get 'search' => 'search#res_search'
	    get 'categories/search' => 'categories#search'
	    get 'sections/search' => 'search#sec_search'
	    get 'nearby' => 'restaurants#nearby'
	  end
	  resources :reviews, except: [:new, :edit]
	  get 'search' => 'search#search'
	  post 'reviews/comment' => 'reviews#comment'
	  get 'review/:id' => 'reviews#get_review'
	  get 'reviews/comment/:id' => 'reviews#showcomment'
	  get 'restaurants/approve/:id' => 'admin#approve_restaurant'
	  get 'restaurants/feature/:id' => 'admin#feature_restaurant'
	  get 'restaurant/bookmarks/follows/:id' => 'restaurants#chk_follow_like'
	  get 'restaurant/unlike/:id' => 'restaurants#unlike'

	  post 'pundit' => 'admin#create_pundit'
	  post 'credit' => 'admin#create_credit_adjust'
	  get 'enable_claim/:id' => 'admin#enable_claim_restaurant'
  end

  post 'block_all_users' => 'users#bolock_all_user'
  post 'reset_db' => 'users#delete_dp'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :photos, except: [:new, :edit]
  
  
  resources :categories, only: [:create, :index]
  
  

  get 'admin/restaurants' => 'admin#index'
  get 'admin/restaurant_pending' => 'admin#rest_pending'
  get 'admin/restaurant_approved' => 'admin#rest_approved'
  get 'admin/restaurant_featured' => 'admin#rest_featured'
  get 'admin/end_users' => 'admin#end_users'
  get 'admin/restaurant_owner' => 'admin#restaurant_users'
  post 'admin/pundit' => 'admin#create_pundit'
  post 'admin/restaurant_owner_create' => 'admin#create_restaurant_owner' , as: 'create_restaurant_owner_admin'
  get 'admin/pundit' => 'admin#pundit'
  get 'admin/pundit_:id' => 'admin#edit_pundit' , as: 'edit_pundit'
  put 'admin/pundit/:id' => 'admin#update_pundit' , as: 'update_pundit'
  patch 'admin/pundit/:id' => 'admin#update_pundit'
  delete 'admin/pundit/:id' => 'admin#delete_pundit' , as: 'del_pundit'
  get 'admin/reviews' => 'admin#alL_reviews'
  get 'admin/checkins' => 'admin#user_checkins'
  get 'admin/posts' => 'admin#user_posts'
  get 'admin/unfeature_:id' => 'admin#unfeature_restaurant' , as: 'unfeature_rest'
  get 'admin/feature_:id' => 'admin#feature_restaurant' , as: 'feature_restaurant_admin'
  get 'admin/unapprove_:id' => 'admin#unapprove_restaurant' , as: 'unaprove_rest'
  get 'admin/approve_:id' => 'admin#approve_restaurant' , as: 'approve_restaurant_admin'
  get 'admin/enable_claim_:id' => 'admin#enable_claim_restaurant' , as: 'enable_claim_restaurant'
  get 'admin/disapprove_claim_:id' => 'admin#disapprove_claim_restaurant' , as: 'disapprove_claim_restaurant'
  get 'admin/restaurant_:id' => 'admin#restaurant_detail' , as: 'restauarant_ad_details'
  get 'admin/credit_history' => 'admin#credit_history' , as: 'credit_history_admin'
  get 'admin/notification_:id' => 'admin#notification' , as: 'superadmin_notification'
  get 'admin/block_:id' => 'admin#end_user_block' , as: 'block_user'
  get 'admin/unblock_:id' => 'admin#end_user_unblock' , as: 'unblock_user'
  get 'admin/versions' => 'admin#give_user_credit' , as: 'give_credits'
  post 'admin/sent_credits' => 'admin#credits_sent' , as: 'sent_credits'
  post 'admin/set_versions' => 'admin#set_version' , as: 'set_version'
  get 'admin/review_delete/:id' => 'admin#delete_review' , as: 'delete_review_admin'
  get 'admin/post_delete/:id' => 'admin#delete_post' , as: 'delete_post_admin'
  post 'admin/transfer_ownership' => 'admin#transfer_ownership' , as: 'transfer_ownership_admin'

  get 'rest_admin/restaurants' => 'restaurant_admin#index' , as: 'owner_restaurants'
  get 'rest_admin/restaurant_:id' => 'restaurant_admin#restaurant_detail' , as: 'restauarant_owner_details'
  post 'rest_admin/search' => 'restaurant_admin#check'
  put 'rest_admin/update_:id' => 'restaurant_admin#update_rest' , as: 'restaurant_update_admin'
  put 'rest_admin/cover_image_:id' => 'restaurant_admin#update_cover_image' , as: 'cover_image_update'
  post 'rest_admin/food_items' => 'restaurant_admin#add_food_item' , as: 'restaurant_add_food_admin'
  get 'rest_admin/food_items_:id' => 'restaurant_admin#food_items' , as: 'restaurant_food_items_admin'
  delete 'rest_admin/food_items_:id' => 'restaurant_admin#delete_fooditem' , as: 'restaurant_food_items_delete_admin'
  put 'rest_admin/food_items_:id' => 'restaurant_admin#update_fooditems' , as: 'restaurant_food_items_update_admin'
  get 'rest_admin/notification_:id' => 'restaurant_admin#notifications' , as: 'restaurant_admin_notification'
  get 'rest_admin/seennotification_:id' => 'restaurant_admin#seen_notification' , as: 'restaurant_admin_seen_notification'
  get 'rest_admin/message_:id' => 'restaurant_admin#messages' , as: 'restaurant_admin_message'
  post 'rest_admin/sendmessage' => 'restaurant_admin#send_message' , as: 'admin_send_messages'
  get 'rest_admin/qrcode_:id' => 'restaurant_admin#qrcode' , as: 'qrcodes_rest_admin'
  post 'rest_admin/qrcode_:id' => 'restaurant_admin#gen_qr' , as: 'qrcode_create_rest_admin'
  get 'rest_admin/qrcodedetail_:id' => 'restaurant_admin#qrdetail' , as: 'qrcodes_detail_rest_admin'
  get 'rest_admin/qrcodedestroy_:id' => 'restaurant_admin#del_qrcode' , as: 'qrcodes_destroy_rest_admin'
  put 'rest_admin/qrcode_edit' => 'restaurant_admin#edit_qrcode' , as: 'qrcode_edit_rest_admin'

  get 'signin' => 'web#signin'
  get 'signup' => 'web#signup'
  get 'signup_detail' => 'web#signup_detail'
  get 'featured_restaurants' => 'web#select_restaurant'
  get 'restaurant_:id' => 'web#restaurant_detail'
  get 'user_:id' => 'web#user_profile'

  

end

app/views/admin/edit_pundit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h3>Update Pundit</h3>
  <%= form_for @user ,  url: update_pundit_path(@user), 'data-no-turbolink' => true , html: { method: :put } do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this pundit from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="box-body">
      <div class="form-group">
        <label for="name">Name</label>
        <%= f.text_field :name , class: 'form-control' , placeholder: 'Enter name' %>
      </div>
      <div class="form-group">
        <label for="Username">Username</label>
        <%= f.text_field :username , class: 'form-control' , placeholder: 'Enter username' %>
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <%= f.text_field :email , class: 'form-control' , placeholder: 'Enter email' %>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <%= f.text_field :password , class: 'form-control' , placeholder: 'Enter password' %>
      </div>
      <div class="form-group">
        <%= f.submit %>
      </div>
    </div>


  <% end %>

</div>

app/views/admin/end_users.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    End Users
    <small></small>
  </h1>
</section>

<div class="row content">
  <div class="col-xs-12">
    <div class="box">
            <!-- <div class="box-header">
              <h3 class="box-title">Reviews</h3>
            </div> -->
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Gender</th>
                    <th>Verified</th>
                    <th>Credit</th>
                    <th>Block</th>
                    <th>Give Credit</th>
                  </tr>
                  </thead>
                  <tbody>
                    <% @user.each do |us| %>
                      <% editi = "give_credit" + us.id.to_s %>
                      <tr>
                        <td><%= us.name %></td>
                        <td><%= us.username %></td>
                        <td><%= us.email %></td>
                        <td><%= us.gender %></td>
                        <td><%= us.verified ? 'Yes' : 'No' %></td>
                        <td><%= us.credit.present? ? us.credit.points : 0%></td>
                        <td><% if us.block  %>
                              <%= link_to "Yes" , unblock_user_path(us.id) %>
                            <% else  %>
                              <%= link_to "No" , block_user_path(us.id) %>
                            <% end  %>
                        </td>
                        <td><%= link_to "Enter", "#"+editi, "data-toggle" => "modal" %></td>
                      </tr>

                      <!-- Modal -->
                      <div class="modal fade" id="<%= editi %>" role="dialog">
                        <div class="modal-dialog">
                        
                          <!-- Modal content-->
                          <div class="modal-content">
                            <div class="modal-header">
                              <button type="button" class="close" data-dismiss="modal">&times;</button>
                              <h4 class="modal-title">Give Credit</h4>
                            </div>
                            <div class="modal-body">
                             <%= form_tag(sent_credits_path , method: "post" , 'data-no-turbolink' => true, :multipart => true) do %>
                              <%= hidden_field_tag(:user_id, us.id) %> 
                                <div class="box-body">
                                  <div class="form-group">
                                    <%= label_tag 'credit', 'Credit'%>
                                    <%= number_field_tag :credit , '' , class: 'form-control', autofocus: true %>
                                  </div>
                                </div>                    
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <%= submit_tag "Done" , class: 'btn btn-default' %>
                              <% end %> 
                            </div>
                          </div>
                          
                        </div>
                      </div>


                    <% end %>
                  </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
  </div>
</div>

app/views/admin/give_user_credit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h3>Latest Andriod Version</h3>
          
    <%= form_tag(set_version_path , method: "post", 'data-no-turbolink' => true) do %>
      <div class="box-body">
        <div class="form-group">
          <%= label_tag 'version', 'Version'%>
          <%= text_field_tag :version , @version.version , class: 'form-control', autofocus: true %>
        </div>
      </div>
      <div class="box-body">
        <div class="form-group">
          <%= label_tag 'force', 'Force Update '%>
          <%= check_box_tag 'force', "yes" , @version.force %>
        </div>
      </div>              

      <div class="box-body">
        <%= submit_tag "Done" , class: 'btn btn-default' %>
      </div>
        <% end %> 

</div>

app/views/admin/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Restaurants
    <small></small>
  </h1>
</section>


<div class="row content">
  <div class="col-xs-12">
    <div class="box">
            <!-- <div class="box-header">
              <h3 class="box-title">Reviews</h3>
            </div> -->
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Active Since</th>
                    <th>Name</th>
                    <!-- <th>Opening Time</th>
                    <th>Closing Time</th> -->
                    <th>Location</th>
                    <th>Approved</th>
                    <th>Featured</th>
                    <th>Claim Credit</th>
                    <th>Owner</th>
                  </tr>
                  </thead>
                  <tbody>
                    <% @restaurant.each do |rest| %>
                      <tr>
                        <td><%= rest.created_at.strftime("%d-%m-%Y") %>
                        <td><%= link_to rest.name , restauarant_ad_details_path(rest.id) %></td>
                        <!-- <td><%= rest.opening_time.strftime("%H:%M %p") %></td>
                        <td><%= rest.closing_time.strftime("%H:%M %p") %></td> -->
                        <td><%= rest.location %></td>
                        <td><% if rest.approved %>
                            <%= link_to "Yes" , unaprove_rest_path(rest.id) %>
                          <% else %>
                            <%= link_to "No" , approve_restaurant_admin_path(rest.id) %>
                          <% end %>
                        </td>
                        <td><% if rest.approved %>
                              <% if rest.featured %>
                                <%= link_to "Yes" , unfeature_rest_path(rest.id) %>
                              <% else %>
                                <%= link_to "No" , feature_restaurant_admin_path(rest.id) %>
                              <% end %>
                            <% else %>
                              <%= rest.featured ? 'Yes' : 'No' %>
                            <% end %> 
                        </td>
                        <td>
                            <% if rest.approved %>
                              <% if rest.claim_credit %>
                                <%= link_to "Yes" , disapprove_claim_restaurant_path(rest.id) %>
                              <% else %>
                                <%= link_to "No" , enable_claim_restaurant_path(rest.id) %>
                              <% end %>
                            <% else %>
                              <%= rest.claim_credit ? 'Yes' : 'No' %>
                            <% end %> 
                          </td>
                          <td><%= rest.owner.name.present? ? rest.owner.name : rest.owner.email %></td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
  </div>
</div>

app/views/admin/pundit.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Pundit
    <small style="float: right;"><button type="button" class="btn btn-info" data-toggle="modal" data-target="#create_pundit">Create Pundit</button></small>
  </h1>
  
  <!-- Modal -->
  <div class="modal fade" id="create_pundit" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Create Pundit</h4>
        </div>
        <div class="modal-body">
          
          <%= form_tag(admin_pundit_path , method: "post", 'data-no-turbolink' => true) do %>
            <div class="box-body">
              <div class="form-group">
                <%= label_tag 'name', 'Name'%>
                <%= text_field_tag :name , '' , class: 'form-control', autofocus: true %>
              </div>
              <div class="form-group">
                <%= label_tag 'username', 'Username'%>
                <%= text_field_tag :username, '' , class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= label_tag 'email', 'Email'%>
                <%= text_field_tag :email , '' , class: 'form-control', autofocus: true %>
              </div>
              <div class="form-group">
                <%= label_tag 'password', 'Password'%>
                <%= text_field_tag :password, '' , class: 'form-control' %>
              </div>
            </div>              


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag "Create" , class: 'btn btn-default' %>
          <% end %> 
        </div>
      </div>
      
    </div>
  </div>
</section>


<div class="row content">
  <div class="col-xs-12">
    <div class="box">
            <!-- <div class="box-header">
              <h3 class="box-title">Reviews</h3>
            </div> -->
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <!-- <th>Gender</th> -->
                    <th>Edit</th>
                    <th>Delete</th>
                  </tr>
                  </thead>
                  <tbody>
                    <% @user.each do |us| %>
                      <tr>
                        <td><%= us.name %></td>
                        <td><%= us.username %></td>
                        <td><%= us.email %></td>
                        <!-- <td><%= us.gender %></td> -->
                        <td><%= link_to "Edit" , edit_pundit_path(us.id) %></td>
                        <td><%= link_to "Delete" , del_pundit_path(us.id) , method: 'DELETE' %></td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
  </div>
</div>

app/views/admin/rest_approved.html.erb
<section class="content-header">
  <h1>
    Restaurants
    <small>Approved</small>
  </h1>
</section>




<div class="row content">
  <div class="col-xs-12">
    <div class="box">
            <!-- <div class="box-header">
              <h3 class="box-title">Reviews</h3>
            </div> -->
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Opening Time</th>
                    <th>Closing Time</th>
                    <th>Location</th>
                    <th>Detail</th>
                  </tr>
                  </thead>
                  <tbody>
                    <% @restaurant.each do |rest| %>
                      <tr>
                        <td><%= rest.name %></td>
                        <td><%= rest.opening_time.strftime("%H:%M %p") %></td>
                        <td><%= rest.closing_time.strftime("%H:%M %p") %></td>
                        <td><%= rest.location %></td>
                        <td><%= link_to 'Details' , restauarant_ad_details_path(rest.id)%></td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
  </div>
</div>

app/views/admin/restaurant_detail.html.erb
<section class="content-header">
  <h1>
    <%= @restaurant.name %>
    <small><%= @restaurant.location %></small>
    <small style="float: right;"><button type="button" class="btn btn-info" data-toggle="modal" data-target="#ownership">Tranfer Ownership</button></small>
    <small style="float: right;"><%= link_to 'Edit' , restauarant_owner_details_path(@restaurant.id), class: 'btn btn-info' %></small>
    <small style="float: right;"><%= link_to 'Back' , url_for(:back) , class: 'btn btn-info' %></small>
  </h1>
</section>


<div class="row content">
  <div class="col-xs-12">
    <div class="box">
            <div class="box-header">
              <h3 class="box-title">Reviews</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="review_table" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Summary</th>
                    <th>Rating</th>
                    <th>Reviewer</th>
                    <th>Review On</th>
                  </tr>
                </thead>
                <tbody>
                  <% @restaurant.reviews.each do |us| %>
                    <tr>
                      <td><%= us.title %></td>
                      <td><%= us.summary %></td>
                      <td><%= us.rating %></td>
                      <td><%= us.reviewer.email %></td>
                      <td><%= us.reviewable_type %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
  </div>
</div>

<div class="row content">
  <div class="col-xs-12">
    <div class="box">
            <div class="box-header">
              <h3 class="box-title">Checkins</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="checkin_table" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Address</th>
                    <th>Post Title</th>
                    <th>User</th>
                  </tr>
                </thead>
                <tbody>
                  <% @restaurant.checkins.each do |us| %>
                    <tr>
                      <td><%= us.address %></td>
                      <td><%= us.post.title %></td>
                      <td><%= us.post.user.email %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
  </div>
</div>

<% if @restaurant.claim_credit %>
<div class="row content">
  <div class="col-xs-12">
    <div class="box">
            <div class="box-header">
              <h3 class="box-title">Credit Claims</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="credit_table" class="dataTables table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Price</th>
                  </tr>
                </thead>
                <tbody>
                  <% @restaurant.credit_histories.each do |us| %>
                    <tr>
                      <td><%= us.user.name %></td>
                      <td><%= us.user.email %></td>
                      <td><%= us.price %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
  </div>
</div>
<% end %>

<div class="modal fade" id="ownership" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Transfer Ownership</h4>
        </div>
        <div class="modal-body">
          <%= form_tag(transfer_ownership_admin_path , method: "post" , :multipart => true , 'data-no-turbolink' => true) do %>
            <div class="box-body">
              <div class="form-group">
                <%= label_tag 'email', 'Email'%>
                <%= text_field_tag :email , params[:email] , class: 'form-control', autofocus: true %>
                <%= hidden_field_tag :id , @restaurant.id , class: 'form-control', autofocus: true %>
              </div>
            </div>
            <!-- /.box-body -->
                     
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Transfer" , class: 'btn btn-default' %>
          <% end %> 
        </div>
      </div>
      
    </div>
  </div>

<script>
  $(function () {
    $("#review_table").DataTable();
    $("#checkin_table").DataTable();
    $("#credit_table").DataTable();
  });
</script>

app/views/admin/restaurant_users.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Restaurant
    <small>Owners</small>
    <small style="float: right;"><button type="button" class="btn btn-info" data-toggle="modal" data-target="#create_owner">Create Restaurant Owner</button></small>
  </h1>

  <!-- Modal -->
  <div class="modal fade" id="create_owner" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Create Restaurant Owner</h4>
        </div>
        <div class="modal-body">
          
          <%= form_tag(create_restaurant_owner_admin_path , method: "post", 'data-no-turbolink' => true) do %>
            <div class="box-body">
              <div class="form-group">
                <%= label_tag 'name', 'Name'%>
                <%= text_field_tag :name , '' , class: 'form-control', autofocus: true %>
              </div>
              <div class="form-group">
                <%= label_tag 'username', 'Username'%>
                <%= text_field_tag :username, '' , class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= label_tag 'email', 'Email'%>
                <%= text_field_tag :email , '' , class: 'form-control', autofocus: true %>
              </div>
              <div class="form-group">
                <%= label_tag 'password', 'Password'%>
                <%= text_field_tag :password, '' , class: 'form-control' %>
              </div>
            </div>              


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag "Create" , class: 'btn btn-default' %>
          <% end %> 
        </div>
      </div>
      
    </div>
  </div>
</section>


<div class="row content">
  <div class="col-xs-12">
    <div class="box">
            <!-- <div class="box-header">
              <h3 class="box-title">Reviews</h3>
            </div> -->
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Gender</th>
                    <th>Verified</th>
                    <th>Restaurants</th>
                  </tr>
                  </thead>
                  <tbody>
                    <% @user.each do |us| %>
                      <tr>
                        <td><%= us.name %></td>
                        <td><%= us.username %></td>
                        <td><%= us.email %></td>
                        <td><%= us.gender.present? ? us.gender : 'Record Missing' %></td>
                        <td><%= us.verified ? 'Yes' : 'No' %></td>
                        <td><% restu = Restaurant.approved.where(owner_id: us.id) %>
                            <% restu.each do |rest| %>
                              <%= link_to rest.name , restauarant_ad_details_path(rest.id) %><br>
                            <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
  </div>
</div>