config/routes.rb
Rails.application.routes.draw do

  root 'web#landing'

  scope 'api' do
    get 'version/:ver' => 'users#version'
	  resources :categories, only: [:create, :index]
	  
	  

	  resources :offers, only: [:index]
	  post 'add_fooditem_image' => 'food_items#add_image'
	  get 'get_users' => 'users#get_users'
	  get 'get_restaurants' => 'restaurants#send_all'
	  put 'user' => 'users#update'
	  patch 'user' => 'users#update'
	  scope "user" do
	    post 'signup' => 'users#create'
	    delete 'signout' => 'users#signout'
	    post 'restaurant/signup' => 'users#restaurant_user_create'
	    post 'signin' => 'users#signin'
	    get 'email/verify/:token' => 'users#verify_email'
	    get 'follow/:id' => 'users#follow'
	    get 'unfollow/:id' => 'users#unfollow'
	    get 'followers' => 'users#followers'
	    post 'reviews' => 'reviews#create_user_review'
	    get 'social/:id' => 'users#social'
	    post 'message/:id' => 'users#message'
	    get 'notifications' => 'users#notifications'
	    get 'all_notifications' => 'push_notification#notifications'
	    get 'notifications/seen' => 'users#notification_seen'
	    post ':type/:id' => 'users#report'
	    resources :posts , except: [:new, :edit , :show]
	    get 'like/:typee/:id' => 'users#likers'
	    get 'unlike/:typee/:id' => 'users#unlike'
	    get 'dislike/:typee/:id' => 'users#dislike' 
	    scope 'posts' do
	      get 'likes/:id' => 'posts#likeable'
	      post 'comment/new' => 'posts#comment'
	      get 'comments/:id' => 'posts#showcomment'
	      resources :checkins, only: [:update]
	    end
	    get 'referral/:referral_code' => 'referral#create'
	    get 'referral' => 'referral#get_users'
	    post 'claim_credit' => 'restaurants#claim_credit'
	    get 'newsfeed' => 'newsfeed#index'
	    get 'localfeed' => 'users#my_feeds'
	    get 'all_feed' => 'newsfeed#localfeed_updated'
	    get 'follows/check/:id' => 'users#chk_follow_user'
	    resources :khaba_history, only: [:index ]
	    get 'credits' => 'khaba_history#credit'

	    get 'bookmarks' => 'users#get_user_likes'

	    post 'eat_buddies' => 'search#find_fb_friends'
	    post 'gcm' => 'push_notification#set_key'
	    post 'profile_picture' => 'users#update_picture'
	    get 'post/:id' => 'posts#get_post'
	  end
	  resources :restaurants, except: [:new, :edit , :show]
	  post 'comment/reply/:id' => 'reply#reply_to_comment'
	  scope "restaurants" do
	    get 'explore' => 'restaurants#explore_rest'
	    post 'qrcode' => 'restaurants#qrcode'
	    get 'featured' => 'restaurants#featuredr'
	    get 'social/:id' => 'restaurants#social'
	    get 'follow/:id' => 'restaurants#follow'
	    get 'unfollow/:id' => 'restaurants#unfollow'
	    post 'reviews' => 'reviews#create_restaurant_review'
	    resources :menus, except: [:new, :edit]
	    scope 'menus' do
	      resources :food_items, except: [:new, :edit]
	    end
	    resources :rating, only: [:create]
	    get 'search' => 'search#res_search'
	    get 'categories/search' => 'categories#search'
	    get 'sections/search' => 'search#sec_search'
	    get 'nearby' => 'restaurants#nearby'
	  end
	  resources :reviews, except: [:new, :edit]
	  get 'search' => 'search#search'
	  post 'reviews/comment' => 'reviews#comment'
	  get 'review/:id' => 'reviews#get_review'
	  get 'reviews/comment/:id' => 'reviews#showcomment'
	  get 'restaurants/approve/:id' => 'admin#approve_restaurant'
	  get 'restaurants/feature/:id' => 'admin#feature_restaurant'
	  get 'restaurant/bookmarks/follows/:id' => 'restaurants#chk_follow_like'
	  get 'restaurant/unlike/:id' => 'restaurants#unlike'

	  post 'pundit' => 'admin#create_pundit'
	  post 'credit' => 'admin#create_credit_adjust'
	  get 'enable_claim/:id' => 'admin#enable_claim_restaurant'
  end

  post 'block_all_users' => 'users#bolock_all_user'
  post 'reset_db' => 'users#delete_dp'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :photos, except: [:new, :edit]
  
  
  resources :categories, only: [:create, :index]
  
  

  get 'admin/restaurants' => 'admin#index'
  get 'admin/restaurant_pending' => 'admin#rest_pending'
  get 'admin/restaurant_approved' => 'admin#rest_approved'
  get 'admin/restaurant_featured' => 'admin#rest_featured'
  get 'admin/end_users' => 'admin#end_users'
  get 'admin/restaurant_owner' => 'admin#restaurant_users'
  post 'admin/pundit' => 'admin#create_pundit'
  post 'admin/restaurant_owner_create' => 'admin#create_restaurant_owner' , as: 'create_restaurant_owner_admin'
  get 'admin/pundit' => 'admin#pundit'
  get 'admin/pundit_:id' => 'admin#edit_pundit' , as: 'edit_pundit'
  put 'admin/pundit/:id' => 'admin#update_pundit' , as: 'update_pundit'
  patch 'admin/pundit/:id' => 'admin#update_pundit'
  delete 'admin/pundit/:id' => 'admin#delete_pundit' , as: 'del_pundit'
  get 'admin/reviews' => 'admin#alL_reviews'
  get 'admin/checkins' => 'admin#user_checkins'
  get 'admin/posts' => 'admin#user_posts'
  get 'admin/unfeature_:id' => 'admin#unfeature_restaurant' , as: 'unfeature_rest'
  get 'admin/feature_:id' => 'admin#feature_restaurant' , as: 'feature_restaurant_admin'
  get 'admin/unapprove_:id' => 'admin#unapprove_restaurant' , as: 'unaprove_rest'
  get 'admin/approve_:id' => 'admin#approve_restaurant' , as: 'approve_restaurant_admin'
  get 'admin/enable_claim_:id' => 'admin#enable_claim_restaurant' , as: 'enable_claim_restaurant'
  get 'admin/disapprove_claim_:id' => 'admin#disapprove_claim_restaurant' , as: 'disapprove_claim_restaurant'
  get 'admin/restaurant_:id' => 'admin#restaurant_detail' , as: 'restauarant_ad_details'
  get 'admin/credit_history' => 'admin#credit_history' , as: 'credit_history_admin'
  get 'admin/notification_:id' => 'admin#notification' , as: 'superadmin_notification'
  get 'admin/block_:id' => 'admin#end_user_block' , as: 'block_user'
  get 'admin/unblock_:id' => 'admin#end_user_unblock' , as: 'unblock_user'
  get 'admin/versions' => 'admin#give_user_credit' , as: 'give_credits'
  post 'admin/sent_credits' => 'admin#credits_sent' , as: 'sent_credits'
  post 'admin/set_versions' => 'admin#set_version' , as: 'set_version'
  get 'admin/review_delete/:id' => 'admin#delete_review' , as: 'delete_review_admin'
  get 'admin/post_delete/:id' => 'admin#delete_post' , as: 'delete_post_admin'
  post 'admin/transfer_ownership' => 'admin#transfer_ownership' , as: 'transfer_ownership_admin'

  get 'rest_admin/restaurants' => 'restaurant_admin#index' , as: 'owner_restaurants'
  get 'rest_admin/restaurant_:id' => 'restaurant_admin#restaurant_detail' , as: 'restauarant_owner_details'
  post 'rest_admin/search' => 'restaurant_admin#check'
  put 'rest_admin/update_:id' => 'restaurant_admin#update_rest' , as: 'restaurant_update_admin'
  put 'rest_admin/cover_image_:id' => 'restaurant_admin#update_cover_image' , as: 'cover_image_update'
  post 'rest_admin/food_items' => 'restaurant_admin#add_food_item' , as: 'restaurant_add_food_admin'
  get 'rest_admin/food_items_:id' => 'restaurant_admin#food_items' , as: 'restaurant_food_items_admin'
  delete 'rest_admin/food_items_:id' => 'restaurant_admin#delete_fooditem' , as: 'restaurant_food_items_delete_admin'
  put 'rest_admin/food_items_:id' => 'restaurant_admin#update_fooditems' , as: 'restaurant_food_items_update_admin'
  get 'rest_admin/notification_:id' => 'restaurant_admin#notifications' , as: 'restaurant_admin_notification'
  get 'rest_admin/seennotification_:id' => 'restaurant_admin#seen_notification' , as: 'restaurant_admin_seen_notification'
  get 'rest_admin/message_:id' => 'restaurant_admin#messages' , as: 'restaurant_admin_message'
  post 'rest_admin/sendmessage' => 'restaurant_admin#send_message' , as: 'admin_send_messages'
  get 'rest_admin/qrcode_:id' => 'restaurant_admin#qrcode' , as: 'qrcodes_rest_admin'
  post 'rest_admin/qrcode_:id' => 'restaurant_admin#gen_qr' , as: 'qrcode_create_rest_admin'
  get 'rest_admin/qrcodedetail_:id' => 'restaurant_admin#qrdetail' , as: 'qrcodes_detail_rest_admin'
  get 'rest_admin/qrcodedestroy_:id' => 'restaurant_admin#del_qrcode' , as: 'qrcodes_destroy_rest_admin'
  put 'rest_admin/qrcode_edit' => 'restaurant_admin#edit_qrcode' , as: 'qrcode_edit_rest_admin'

  get 'signin' => 'web#signin'
  get 'signup' => 'web#signup'
  get 'signup_detail' => 'web#signup_detail'
  get 'featured_restaurants' => 'web#select_restaurant'
  get 'restaurant_:id' => 'web#restaurant_detail'
  get 'user_:id' => 'web#user_profile'

  

end

app/controllers/restaurant_admin_controller.rb
class RestaurantAdminController < ApplicationController
	before_filter :authenticate_user!
	before_filter :is_restaurant_owner
	layout "rest_admin"

	def index
		@restaurant = Restaurant.where(owner_id: @current_user.id)
	end

	def restaurant_detail
		if @current_user.role == 'admin'
			@restaurant = Restaurant.find(params[:id])
		else
			@restaurant = Restaurant.where(owner_id: @current_user.id).find(params[:id])
		end
	end

	def check
		p params
		if params[:image].present?
			restaurant = Restaurant.new(name: params[:name] , typee: params[:typee] , location: params[:location] , opening_time: params[:opening_time].first , closing_time: params[:closing_time].first , per_head: params[:cost])
			restaurant.owner_id = @owner.id
			if restaurant.save
		        c_image = CoverImage.create(:image => params[:image][:image] , :restaurant_id => restaurant.id)
		        if params[:call_now].present?
		        	cal = CallNow.create(:number => params[:call_now] , :restaurant_id => restaurant.id)
		        end
				redirect_to :back , notice: 'Successfully Created'
			else
				redirect_to :back , notice: 'Unprocessable Entity'
			end
		else
			redirect_to :back , notice: 'Cover Image Missing'
		end
	end

	def update_cover_image
		p params
		if params[:image][:image].present?
			if @current_user.role == 'admin'
				rest = Restaurant.find(params[:id])
			else
				rest = Restaurant.where(owner_id: @current_user.id).find(params[:id])
			end
			if rest.cover_image.present?
				rest.cover_image.update(image: params[:image][:image])
			else
				cov  =CoverImage.create(image: params[:image][:image] , :restaurant_id => rest.id)
			end
		end
		redirect_to :back
	end

	def update_rest
		p params
		if @current_user.role == 'admin'
			res = Restaurant.find(params[:id])
		else
			res = Restaurant.where(owner_id: @current_user.id).find(params[:id])
		end
		res.update(rest_update_params)
		if params[:image].present?
			if res.cover_image.present?
				res.cover_image.update(params[:image][:image])
			else
				cov  =CoverImage.create(image: params[:image][:image] , :restaurant_id => res.id)
			end
		end
		redirect_to :back
	end

	def add_food_item
		p params
		if params[:name].present? && params[:fooditem][:price].present? && ( params[:section].present? || params[:menu_section].present? )
			cat_foo = false
			if @current_user.role == 'admin'
				restaurant = Restaurant.find(params[:restaurant_id])
			else
				restaurant = Restaurant.where(owner_id: @current_user.id).find(params[:restaurant_id])
			end
			if restaurant.menu.nil?
				menur = Menu.create(name: 'Menu', summary: 'Menu', restaurant_id: restaurant.id)
			else
				menur = restaurant.menu
			end

			if params[:section].present?
				if menur.sections.where(title: params[:section]).count > 0
					sec = menur.sections.find_by_title(params[:section])
				else
					sec = Section.create(title: params[:section] , menu_id: menur.id)
				end
			else
				sec = menur.sections.find(params[:menu_section])
			end
			fooditem = FoodItem.create(name: params[:name], price: params[:fooditem][:price], section_id: sec.id)

			if params[:categories].present?
				params[:categories].each do |cat|
					fooditem.categories << Category.find(cat.to_i)
					cat_foo = true
				end
			end

			if params[:new_category].present?
				categ = Category.create(name: params[:new_category])
				fooditem.categories << categ
				cat_foo = true
			end

			if cat_foo == false
				if Category.where(name: 'Uncategorized').count > 0
					 cate_uncat = Category.find_by_name('Uncategorized')
				else
					cate_uncat = Category.create(name: 'Uncategorized')
				end
				fooditem.categories << cate_uncat
			end

			if params[:image].present?
				params[:image][:image].each do |img|
					photo = Photo.create(image: img , imageable_id: fooditem.id, imageable_type: 'FoodItem')
				end
			end
		end
		redirect_to :back
	end

	def food_items
		p params
		if @current_user.role == 'admin'
			@restaurant = Restaurant.find(params[:id])
		else
			@restaurant = Restaurant.where(owner_id: @current_user.id).find(params[:id])
		end
		unless @restaurant.menu.nil?
			@food_items = @restaurant.menu.sections
		else
			sumr = @restaurant.name + ' menu'
			menu = Menu.create(name: 'Menu' , summary: sumr, restaurant_id: @restaurant.id)
			redirect_to request.original_url
		end
	end

	def update_fooditems
		p params
		food = FoodItem.find(params[:id])
		food.update(fooditem_params)
		if params[:section].present?
			menu = Menu.find(params[:menu_id])
			if menu.sections.where(title: params[:section]).count > 0
				sec = menu.sections.where(title: params[:section]).first
			else
				sec = Section.create(title: params[:section] , menu_id: params[:menu_id])
			end
			food.update(section_id: sec.id)
		end
		if params[:re_categories].present?
			params[:re_categories].each do |cat|
				food.categories.delete(cat.to_i)
			end
		end
		if params[:ad_categories].present?
			params[:ad_categories].each do |cat|
				if food.categories.where(id: cat.to_i).count < 1
					food.categories << Category.find(cat.to_i)
				end
			end
		end
		redirect_to :back
	end

	def delete_fooditem
		if @current_user.role == 'admin'
			restaurant = Restaurant.find(params[:restaurant_id])
		else
			restaurant = Restaurant.where(owner_id: @current_user.id).find(params[:restaurant_id])
		end
		fooditem = FoodItem.find(params[:id])
		if fooditem.section.menu.restaurant.id == restaurant.id
			fooditem.destroy
		end
		redirect_to :back
	end

	def notifications
		if @current_user.role == 'admin'
			@restaurant = Restaurant.find(params[:id])
		else
			@restaurant = Restaurant.where(owner_id: @current_user.id).find(params[:id])
		end
		@notifications = @restaurant.notifications
	end

	def seen_notification
		@notification = Notification.find(params[:id])
		unless @notification.seen
			@notification.update(seen: true)
		end
		redirect_to :back
	end

	def messages
		@restaurant = Restaurant.where(owner_id: @current_user.id).find(params[:id])
		@message = Message.where(reciever_type: 'Restaurant').where(reciever_id: @restaurant.id)
	end

	def send_message
		mes = Message.create(body: params[:reply] , sender_id: params[:restaurant_id] , sender_type: 'Restaurant' , reciever_id: params[:user_id] , reciever_type: 'User')
		Message.find(params[:message_id]).update(status: 1)
		redirect_to :back
	end

	def gen_qr
		p params
		if params[:image].present? && params[:max_credit].present?
			qr = Qrcode.create(points: params[:points] , description: params[:description] , restaurant_id: params[:id] , max_credit: params[:max_credit])
			of = OfferImage.create(image: params[:image][:image] , qrcode_id: qr.id)
		end
		redirect_to :back
	end

	def qrcode
		if @current_user.role == 'admin'
			@restaurant = Restaurant.find(params[:id])
		else
			@restaurant = Restaurant.where(owner_id: @current_user.id).find(params[:id])
		end
		@qrcode = @restaurant.qrcodes.order(created_at: 'DESC')
	end

	def qrdetail
		@qr = Qrcode.find(params[:id])
		if @current_user.role == 'admin'
			@qrcode = @qr.credit_histories
		else
			@qrcode = Restaurant.where(owner_id: @current_user.id).find(@qr.restaurant.id).qrcodes.find(params[:id]).credit_histories
		end
	end

	def del_qrcode
		@qr = Qrcode.find(params[:id])
		if @current_user.role == 'admin'
			@qr.destroy
		else
			@qrcode = Restaurant.where(owner_id: @current_user.id).find(@qr.restaurant.id).qrcodes.find(params[:id])
			@qrcode.destroy
		end
		redirect_to :back
	end

	def edit_qrcode
		if qr = Qrcode.find(params[:qrcode_id])
			qr.update(max_credit: params[:max_cre])
		end
		redirect_to :back
	end

	private
	def rest_update_params
		params.require(:restaurant).permit(:name , :opening_time , :closing_time , :location )
	end

	def fooditem_params
		params.require(:food_item).permit(:name , :price)
	end

end

app/helpers/restaurant_admin_helper.rb
module RestaurantAdminHelper
end

app/views/restaurant_admin/restaurant_detail.html.erb
<style type="text/css">
  .modal{
      z-index: 20;   
  }
  .modal-backdrop{
      z-index: 10;        
  }​
</style>
<section class="content-header">
  <h1>
    <%= @restaurant.name %>
    <small ><%= @restaurant.location.present? ? @restaurant.location.truncate(40) : '' %></small>
    <% if @current_user.role == 'admin' %>
      <small style="float: right;"><%= link_to 'Back' , url_for(:back) , class: 'btn btn-info' %></small>
    <% end %>
    <small style="float: right;"><button type="button" class="btn btn-info" data-toggle="modal" data-target="#edit_restaurant">Edit</button></small>
    <small style="float: right;"><button type="button" class="btn btn-info" data-toggle="modal" data-target="#cover_image">Change CoverImage</button></small>
    <% if @restaurant.claim_credit %>
    <small style="float: right;"><%= link_to 'QR Code' , qrcodes_rest_admin_path(@restaurant.id), class: 'btn btn-info' %></small>
    <% end %>
    <small style="float: right;"><%= link_to 'Notification' , restaurant_admin_notification_path(@restaurant.id) , class: 'btn btn-info' %></small>
    <!-- <small style="float: right;"><%= link_to 'Message' , restaurant_admin_message_path(@restaurant.id) , class: 'btn btn-info' %></small> -->
    <small style="float: right;"><%= link_to 'Menu' , restaurant_food_items_admin_path(@restaurant.id), class: 'btn btn-info' %></small>
  </h1>

  <!-- Modal -->
  <div class="modal fade" id="edit_restaurant" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit Restaurant</h4>
        </div>
        <div class="modal-body">
          <%= form_for @restaurant ,  url: restaurant_update_admin_path(@restaurant), 'data-no-turbolink' => true, html: { method: :put } do |f| %>
            <% if @restaurant.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

                <ul>
                <% @restaurant.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="box-body">
              <div class="form-group">
                <%= f.label 'name', 'Name'%>
                <%= f.text_field :name, class: 'form-control', autofocus: true %>
              </div>
              <div class="form-group">
                <%= f.label 'opening_time', 'Opening Time'%>
                <%= f.time_field :opening_time , class: 'form-control', autofocus: true %>
              </div>
              <div class="form-group">
                <%= f.label 'closing_time', 'Closing Time'%>
                <%= f.time_field :closing_time  , class: 'form-control', autofocus: true %>
              </div>
              <div class="form-group">
                <%= f.label 'location', 'Location'%>
                <div id="map" class="form-group" style="height: 150px;"></div>
                <%= f.text_field :location  , class: 'form-control', autofocus: true %>
              </div>
              <!-- <div class="form-group">
                <%= f.label 'image', 'Image'%>
                <%= file_field( "image", "image" ) %>
              </div> -->
            </div>


                     
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Update" , class: 'btn btn-default' %>
          <% end %> 
        </div>
      </div>
      
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="cover_image" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Change Cover Image</h4>
        </div>
        <div class="modal-body">
          <%= form_tag(cover_image_update_path(@restaurant) , method: "put" , :multipart => true , 'data-no-turbolink' => true) do %>

            <div class="box-body">
              <div class="form-group">
                <%= label_tag 'image', 'Image'%>
                <%= file_field( "image", "image" ) %>
              </div>
            </div>
                     
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= submit_tag "Update" , class: 'btn btn-default' %>
          <% end %> 
        </div>
      </div>
      
    </div>
  </div>

</section>


<div class="row content">
  <div class="col-xs-12">
    <div class="box">
            <div class="box-header">
              <h3 class="box-title">Reviews</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="review_table" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Summary</th>
                    <th>Rating</th>
                    <th>Reviewer</th>
                    <th>Review On</th>
                    <th>Time</th>
                  </tr>
                </thead>
                <tbody>
                  <% @restaurant.reviews.each do |us| %>
                    <tr>
                      <td><%= us.title %></td>
                      <td><%= us.summary %></td>
                      <td><%= us.rating %></td>
                      <td><%= us.reviewer.email %></td>
                      <td><%= us.reviewable_type %></td>
                      <td><%= us.updated_at.strftime('%H:%M %F') %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
  </div>
</div>

<div class="row content">
  <div class="col-xs-12">
    <div class="box">
            <div class="box-header">
              <h3 class="box-title">Checkins</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="checkin_table" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Address</th>
                    <th>Post Title</th>
                    <th>User</th>
                    <th>Time</th>
                  </tr>
                </thead>
                <tbody>
                  <% @restaurant.checkins.each do |us| %>
                    <tr>
                      <td><%= us.address %></td>
                      <td><%= us.post.title %></td>
                      <td><%= us.post.user.email %></td>
                      <td><%= us.updated_at.strftime('%H:%M %F') %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
  </div>
</div>

<% if @restaurant.claim_credit %>

<div class="row content">
  <div class="col-xs-12">
    <div class="box">
            <div class="box-header">
              <h3 class="box-title">Credit Claims</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="credit_table" class="dataTables table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Price</th>
                    <th>Time</th>
                  </tr>
                </thead>
                <tbody>
                  <% @restaurant.credit_histories.each do |us| %>
                    <tr>
                      <td><%= us.user.name %></td>
                      <td><%= us.user.email %></td>
                      <td><%= us.price %></td>
                      <td><%= us.updated_at.strftime('%H:%M %F') %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
  </div>
</div>

<% end %>

<script>
  $(function () {
    $("#review_table").DataTable();
    $("#checkin_table").DataTable();
    $("#credit_table").DataTable();
  });
</script>

<script>
    var markersArray = [];
    function clearOverlays() {
  for (var i = 0; i < markersArray.length; i++ ) {
    markersArray[i].setMap(null);
  }
  markersArray.length = 0;
}


      function initMap() {
        var input = document.getElementById('restaurant_location');
        console.log("initilalizing map");
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat:   -40.900557, lng: 174.885971},
          zoom: 16


          
        });

      $(document).ready(function(){

        var marker1;

        var marker0;

      });

        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };

            map.setCenter(pos);
          }, function() {
            //handleLocationError(true, infoWindow, map.getCenter());
          });
        } else {
          // Browser doesn't support Geolocation
          //handleLocationError(false, infoWindow, map.getCenter());
        }
      

      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
      }
        

        var autocomplete = new google.maps.places.Autocomplete(input);
        autocomplete.bindTo('bounds', map);

        //map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        var infowindow = new google.maps.InfoWindow();
        var marker = new google.maps.Marker({
          map: map
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });

        autocomplete.addListener('place_changed', function() {
          infowindow.close();
          var place = autocomplete.getPlace();
          if (!place.geometry) {
            return;
          }

          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);
          }

        });

      }
  function setMapOnAll(map) {
    for (var i = 0; i < marker1.length; i++) {
      marker1[i].setMap(map);
    }
  }

  // Removes the markers from the map, but keeps them in the array.
  function clearMarkers() {
    setMapOnAll(map);
  }


    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBoUyblkGqwp2lFuWQb0v_-J_mI5sYJYPc&libraries=places&callback=initMap" async defer></script>