config/routes.rb
Rails.application.routes.draw do

  root 'web#landing'

  scope 'api' do
    get 'version/:ver' => 'users#version'
	  resources :categories, only: [:create, :index]
	  
	  

	  resources :offers, only: [:index]
	  post 'add_fooditem_image' => 'food_items#add_image'
	  get 'get_users' => 'users#get_users'
	  get 'get_restaurants' => 'restaurants#send_all'
	  put 'user' => 'users#update'
	  patch 'user' => 'users#update'
	  scope "user" do
	    post 'signup' => 'users#create'
	    delete 'signout' => 'users#signout'
	    post 'restaurant/signup' => 'users#restaurant_user_create'
	    post 'signin' => 'users#signin'
	    get 'email/verify/:token' => 'users#verify_email'
	    get 'follow/:id' => 'users#follow'
	    get 'unfollow/:id' => 'users#unfollow'
	    get 'followers' => 'users#followers'
	    post 'reviews' => 'reviews#create_user_review'
	    get 'social/:id' => 'users#social'
	    post 'message/:id' => 'users#message'
	    get 'notifications' => 'users#notifications'
	    get 'all_notifications' => 'push_notification#notifications'
	    get 'notifications/seen' => 'users#notification_seen'
	    post ':type/:id' => 'users#report'
	    resources :posts , except: [:new, :edit , :show]
	    get 'like/:typee/:id' => 'users#likers'
	    get 'unlike/:typee/:id' => 'users#unlike'
	    get 'dislike/:typee/:id' => 'users#dislike' 
	    scope 'posts' do
	      get 'likes/:id' => 'posts#likeable'
	      post 'comment/new' => 'posts#comment'
	      get 'comments/:id' => 'posts#showcomment'
	      resources :checkins, only: [:update]
	    end
	    get 'referral/:referral_code' => 'referral#create'
	    get 'referral' => 'referral#get_users'
	    post 'claim_credit' => 'restaurants#claim_credit'
	    get 'newsfeed' => 'newsfeed#index'
	    get 'localfeed' => 'users#my_feeds'
	    get 'all_feed' => 'newsfeed#localfeed_updated'
	    get 'follows/check/:id' => 'users#chk_follow_user'
	    resources :khaba_history, only: [:index ]
	    get 'credits' => 'khaba_history#credit'

	    get 'bookmarks' => 'users#get_user_likes'

	    post 'eat_buddies' => 'search#find_fb_friends'
	    post 'gcm' => 'push_notification#set_key'
	    post 'profile_picture' => 'users#update_picture'
	    get 'post/:id' => 'posts#get_post'
	  end
	  resources :restaurants, except: [:new, :edit , :show]
	  post 'comment/reply/:id' => 'reply#reply_to_comment'
	  scope "restaurants" do
	    get 'explore' => 'restaurants#explore_rest'
	    post 'qrcode' => 'restaurants#qrcode'
	    get 'featured' => 'restaurants#featuredr'
	    get 'social/:id' => 'restaurants#social'
	    get 'follow/:id' => 'restaurants#follow'
	    get 'unfollow/:id' => 'restaurants#unfollow'
	    post 'reviews' => 'reviews#create_restaurant_review'
	    resources :menus, except: [:new, :edit]
	    scope 'menus' do
	      resources :food_items, except: [:new, :edit]
	    end
	    resources :rating, only: [:create]
	    get 'search' => 'search#res_search'
	    get 'categories/search' => 'categories#search'
	    get 'sections/search' => 'search#sec_search'
	    get 'nearby' => 'restaurants#nearby'
	  end
	  resources :reviews, except: [:new, :edit]
	  get 'search' => 'search#search'
	  post 'reviews/comment' => 'reviews#comment'
	  get 'review/:id' => 'reviews#get_review'
	  get 'reviews/comment/:id' => 'reviews#showcomment'
	  get 'restaurants/approve/:id' => 'admin#approve_restaurant'
	  get 'restaurants/feature/:id' => 'admin#feature_restaurant'
	  get 'restaurant/bookmarks/follows/:id' => 'restaurants#chk_follow_like'
	  get 'restaurant/unlike/:id' => 'restaurants#unlike'

	  post 'pundit' => 'admin#create_pundit'
	  post 'credit' => 'admin#create_credit_adjust'
	  get 'enable_claim/:id' => 'admin#enable_claim_restaurant'
  end

  post 'block_all_users' => 'users#bolock_all_user'
  post 'reset_db' => 'users#delete_dp'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :photos, except: [:new, :edit]
  
  
  resources :categories, only: [:create, :index]
  
  

  get 'admin/restaurants' => 'admin#index'
  get 'admin/restaurant_pending' => 'admin#rest_pending'
  get 'admin/restaurant_approved' => 'admin#rest_approved'
  get 'admin/restaurant_featured' => 'admin#rest_featured'
  get 'admin/end_users' => 'admin#end_users'
  get 'admin/restaurant_owner' => 'admin#restaurant_users'
  post 'admin/pundit' => 'admin#create_pundit'
  post 'admin/restaurant_owner_create' => 'admin#create_restaurant_owner' , as: 'create_restaurant_owner_admin'
  get 'admin/pundit' => 'admin#pundit'
  get 'admin/pundit_:id' => 'admin#edit_pundit' , as: 'edit_pundit'
  put 'admin/pundit/:id' => 'admin#update_pundit' , as: 'update_pundit'
  patch 'admin/pundit/:id' => 'admin#update_pundit'
  delete 'admin/pundit/:id' => 'admin#delete_pundit' , as: 'del_pundit'
  get 'admin/reviews' => 'admin#alL_reviews'
  get 'admin/checkins' => 'admin#user_checkins'
  get 'admin/posts' => 'admin#user_posts'
  get 'admin/unfeature_:id' => 'admin#unfeature_restaurant' , as: 'unfeature_rest'
  get 'admin/feature_:id' => 'admin#feature_restaurant' , as: 'feature_restaurant_admin'
  get 'admin/unapprove_:id' => 'admin#unapprove_restaurant' , as: 'unaprove_rest'
  get 'admin/approve_:id' => 'admin#approve_restaurant' , as: 'approve_restaurant_admin'
  get 'admin/enable_claim_:id' => 'admin#enable_claim_restaurant' , as: 'enable_claim_restaurant'
  get 'admin/disapprove_claim_:id' => 'admin#disapprove_claim_restaurant' , as: 'disapprove_claim_restaurant'
  get 'admin/restaurant_:id' => 'admin#restaurant_detail' , as: 'restauarant_ad_details'
  get 'admin/credit_history' => 'admin#credit_history' , as: 'credit_history_admin'
  get 'admin/notification_:id' => 'admin#notification' , as: 'superadmin_notification'
  get 'admin/block_:id' => 'admin#end_user_block' , as: 'block_user'
  get 'admin/unblock_:id' => 'admin#end_user_unblock' , as: 'unblock_user'
  get 'admin/versions' => 'admin#give_user_credit' , as: 'give_credits'
  post 'admin/sent_credits' => 'admin#credits_sent' , as: 'sent_credits'
  post 'admin/set_versions' => 'admin#set_version' , as: 'set_version'
  get 'admin/review_delete/:id' => 'admin#delete_review' , as: 'delete_review_admin'
  get 'admin/post_delete/:id' => 'admin#delete_post' , as: 'delete_post_admin'
  post 'admin/transfer_ownership' => 'admin#transfer_ownership' , as: 'transfer_ownership_admin'

  get 'rest_admin/restaurants' => 'restaurant_admin#index' , as: 'owner_restaurants'
  get 'rest_admin/restaurant_:id' => 'restaurant_admin#restaurant_detail' , as: 'restauarant_owner_details'
  post 'rest_admin/search' => 'restaurant_admin#check'
  put 'rest_admin/update_:id' => 'restaurant_admin#update_rest' , as: 'restaurant_update_admin'
  put 'rest_admin/cover_image_:id' => 'restaurant_admin#update_cover_image' , as: 'cover_image_update'
  post 'rest_admin/food_items' => 'restaurant_admin#add_food_item' , as: 'restaurant_add_food_admin'
  get 'rest_admin/food_items_:id' => 'restaurant_admin#food_items' , as: 'restaurant_food_items_admin'
  delete 'rest_admin/food_items_:id' => 'restaurant_admin#delete_fooditem' , as: 'restaurant_food_items_delete_admin'
  put 'rest_admin/food_items_:id' => 'restaurant_admin#update_fooditems' , as: 'restaurant_food_items_update_admin'
  get 'rest_admin/notification_:id' => 'restaurant_admin#notifications' , as: 'restaurant_admin_notification'
  get 'rest_admin/seennotification_:id' => 'restaurant_admin#seen_notification' , as: 'restaurant_admin_seen_notification'
  get 'rest_admin/message_:id' => 'restaurant_admin#messages' , as: 'restaurant_admin_message'
  post 'rest_admin/sendmessage' => 'restaurant_admin#send_message' , as: 'admin_send_messages'
  get 'rest_admin/qrcode_:id' => 'restaurant_admin#qrcode' , as: 'qrcodes_rest_admin'
  post 'rest_admin/qrcode_:id' => 'restaurant_admin#gen_qr' , as: 'qrcode_create_rest_admin'
  get 'rest_admin/qrcodedetail_:id' => 'restaurant_admin#qrdetail' , as: 'qrcodes_detail_rest_admin'
  get 'rest_admin/qrcodedestroy_:id' => 'restaurant_admin#del_qrcode' , as: 'qrcodes_destroy_rest_admin'
  put 'rest_admin/qrcode_edit' => 'restaurant_admin#edit_qrcode' , as: 'qrcode_edit_rest_admin'

  get 'signin' => 'web#signin'
  get 'signup' => 'web#signup'
  get 'signup_detail' => 'web#signup_detail'
  get 'featured_restaurants' => 'web#select_restaurant'
  get 'restaurant_:id' => 'web#restaurant_detail'
  get 'user_:id' => 'web#user_profile'

  

end

app/views/web/restaurant_detail.html.erb
<link rel="stylesheet" href="css/main.css">
<link rel="stylesheet" href="css/rest_detail_nav.css">

<% if @restaurant.cover_image.present? %>
<style type="text/css">
    .a-banner-section{
        background: rgba(0, 0, 0, 0) url('<%= @restaurant.cover_image.image_url %>') no-repeat scroll 0 0 / cover ;
    }
</style>
<% else %>
<style type="text/css">
    .a-banner-section{
        background: rgba(0, 0, 0, 0) url('img/banner.png') no-repeat scroll 0 0 / cover ;
    }
</style>
<% end %>
<header class="a-header">
	<nav class="a-top-bar">
    	<div class="container-fluid">
    		<div class="row">
    			<div class="col-md-8 col-sm-8 col-xs-12">
    				<div class="logo">
        				<a href="#"><img src="img/logo_03.png" alt="image descraption"></a>
        			</div>
            	</div>
                <div class="col-md-4 col-sm-4 col-xs-12" style="margin-top: 15px;">
                	<a href="#"><span class="food"><span>Foot Pandits</span></span></a>
                	<a href="<%= signin_path %>"><span class="login"><span>Login</span></span></a>
                </div>
    		</div>
        </div>
    </nav>
    <section class="a-banner-section">
    	<div class="container">
    		 <form role="form" class="a-search-form">
				<div class="input-group input-group-lg">
				  	<span class="input-group-addon" id="sizing-addon1"><i class="fa fa-search" aria-hidden="true"></i></span>
					<input type="text" class="form-control" placeholder="Search for Resturant, Dishes & Foodies ">
					<span class="input-group-btn">
				        <button class="btn btn-secondary" type="button">search</button>
				    </span>
				</div>
			</form>
			<div class="arcadian-cafe">
				<h2><%= @restaurant.name %></h2>
				<ul>
					<li><a href="javascript:;"><i class="fa fa-search" aria-hidden="true"></i></a></li>
					<li><a href="javascript:;"><i class="fa fa-search" aria-hidden="true"></i></a></li>
					<li><a href="javascript:;"><i class="fa fa-user-plus" aria-hidden="true"></i></a></li>
					<li><a href="javascript:;"><i class="fa fa-search" aria-hidden="true"></i>Write Review</a></li>
					<li><a href="javascript:;"><i class="fa fa-search" aria-hidden="true"></i></a></li>
				</ul>
			</div>
			<div class="a-rating">
				<div class="public-rating">
					<h3>Public Rating</h3>
					<strong><%= @rating %></strong>
					<span><%= @coun %> votes</span>
				</div>
			</div>
    	</div>
    </section>
</header>
<div class="container">
    <main class="a-main-content">
		<aside class="a-sidebar-left">
			<article class="a-address-block clearfix">
				<div class="a-number">
					<h4>Phone Number</h4>
					<a href="javascript:;"><%= @call_now.present? ? @call_now.number : 'Number Missing' %></a>
				</div>
				<div class="a-address">
					<h4>Address</h4>
					<p><%= @restaurant.location %></p>
				</div>
			</article>
			<article class="a-cuisines-block">
				<h4>Cuisines</h4>
				<ul class="clearfix">
					<li><a href="javascript:;">Chinese</a></li>
					<li><a href="javascript:;">Indians</a></li>
					<li><a href="javascript:;">Pakistanis</a></li>
					<li><a href="javascript:;">Chinese</a></li>
					<li><a href="javascript:;">Indians</a></li>
				</ul>
			</article>
			<article class="a-dishes-block">
				<h4>Recommended Dishes</h4>
				<ul class="clearfix">
					<li><a href="javascript:;">Burger</a></li>
					<li><a href="javascript:;">Burger</a></li>
					<li><a href="javascript:;">Burger</a></li>
					<li><a href="javascript:;">Burger</a></li>
					<li><a href="javascript:;">Burger</a></li>
				</ul>
			</article>
			<article class="a-costPerPerson-block">
				<h4>Cost per Person</h4>
				<p>PKR 750 - PKR 1000</p>
			</article>
			<figure>
				<img src="img/burger.png" alt="">
			</figure>
		</aside>
		<div class="a-middle-content">
			<div class="a-tabs-section" id="my_bar">
				<ul class="nav nav-tabs">
					<li class="active"><a data-toggle="tab" href="#reviews">Reviews</a></li>
					<li><a data-toggle="tab" href="#photos">Photos</a></li>
					<li><a data-toggle="tab" href="#menus">Menus</a></li>
				</ul>
				<div class="tab-content">
					<div id="menus" class="tab-pane fade">
						<h3>MENU</h3>
                        <% @menu.each do |sect| %>
						<h4><%= sect.title %></h4>
                        <% sect.food_items.each do |food_item| %>
                        <div class="reviews-item">
                        	<div class="item-detail">
                                <% if food_item.photos.count > 0 %>
                                <img src="<%= food_item.photos.first.image_url %>" alt="image descrp" style="height: 108px;width: 108px;border-radius: 10px;">
                                <% else %>
                            	<img src="img/paratha-roll.png" alt="image descrp">
                                <% end %>
                                <span><%= food_item.name %></span>
                        	</div>
                            <div class="item-price">
                            	<span>Rs. <%= food_item.price %></span>
                            </div>
                        </div>
                        <% end %>
                        <!-- <div class="reviews-item">
                        	<div class="item-detail">
                            	<img src="img/paratha-roll.png" alt="image descrp">
                                <span>Paratha Roll</span>
                        	</div>
                            <div class="item-price">
                            	<span>Rs. 100</span>
                            </div>
                        </div>
                        <div class="reviews-item">
                        	<div class="item-detail">
                            	<img src="img/paratha-roll.png" alt="image descrp">
                                <span>Paratha Roll</span>
                        	</div>
                            <div class="item-price">
                            	<span>Rs. 100</span>
                            </div>
                        </div>
                        <div class="reviews-item">
                        	<div class="item-detail">
                            	<img src="img/paratha-roll.png" alt="image descrp">
                                <span>Paratha Roll</span>
                        	</div>
                            <div class="item-price">
                            	<span>Rs. 100</span>
                            </div>
                        </div> -->
                        <% end %>
					</div>
					<div id="photos" class="tab-pane fade">
						<h3>PHOTO</h3>
						<!-- <p>Some content in menu 1.</p> -->
                        <% @photos.each do |phot| %>
                        <div class="col-md-4">
                            <img src="<%= phot.image_url %>" class="img-rounded" alt="image" width="108" height="108" >
                        </div>
                        <% end %>
					</div>
					<div id="reviews" class="tab-pane fade in active">
                        <h3>REVIEW</h3>
                        <% @reviews.each do |review| %>
						<h3><%= review.title %></h3>
						<p><%= review.summary %></p>
                        <% end %>
					</div>
				</div>
			</div>
		</div>
        <aside class="a-sidebar-right">
        	<div class="food-photo">
            	<h3>Photos</h3>
                <% @photos.order(created_at: 'DESC').limit(6).each do |phot| %>
                    <img src="<%= phot.image_url %>" class="img-rounded" alt="image" width="92" height="92" >
                <% end %>
            </div>
            <div class="food-photo">
            	<h3>People Been There</h3>
                <% @checkins.each do |checkin| %>
                    <% if checkin.post.user.avatar.present? %>
                    <img src="<%= checkin.post.user.avatar %>" alt="image descrp" class="img-circle" width="53" height="53">
                    <% else %>
                    <img src="img/man01.png" alt="image descrp">
                    <% end %>
                <% end %>
            </div>
            <img src="img/burger.png" alt="image descrp">
        </aside>
    </main>
</div>
	

<footer class="footer">
	<div class="container">
    	<div class="footer-border">
            <div class="footer-iner">
                <div class="row">
                    <div class="col-md-3 col-sm-2 col-xs-12">
                    	<h2>Businesses</h2>
                        <span>Add a Restaurant</span>
                        <span>Claim your Listing</span>
                        <span>Business App</span>
                        <span>Restaurant Widgetst</span>
                        <span>Guidelines</span>
                        <span>Business Blog</span>
                    </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                    	<h2><br></h2>
                        <span>Advertise</span>
                        <span>Book</span>
                        <span>Order</span>
                        <span>Base</span>
                        <span>Whitelabel</span>
                    </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                    	<h2>Countries</h2>
                        <span>Australia</span>
                        <span>Brasil</span>
                        <span>Canada</span>
                        <span>Chile</span>
                        <span>Czech Republic</span>
                        <span>India</span>
                        <span>Indonesia</span>
                        <span>Ireland</span>
                    </div>
                    <div class="col-md-2 col-sm-2 col-xs-12">
                    	<h2><br></h2>
                        <span>Itly</span>
                        <span>Lebanon</span>
                        <span>Malaysia</span>
                        <span>New Zealand</span>
                        <span>Philippines</span>
                        <span>Poland</span>
                        <span>Portugal</span>
                        <span>Qatar</span>
                    </div>
                    <div class="col-md-3 col-sm-2 col-xs-12">
                    	<h2><br></h2>
                        <span>Slovakia</span>
                        <span>South Africa</span>
                        <span>Sri Lanka</span>
                        <span>Turkey</span>
                        <span>UAE</span>
                        <span>United Kingdom</span>
                        <span>United States</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
.erb

app/views/web/select_restaurant.html.erb
<link rel="stylesheet" type="text/css" href="css/ns-default.css" />
<link rel="stylesheet" type="text/css" href="css/ns-style-bar.css" />
<link rel="stylesheet" type="text/css" href="css/style.css">

<div id="wrapper" style="background-color: #e4761d;">
	<header class="select_rest" role="main">
        <nav class="nav-top" id="sel_rest_zindex">
        	<div class="container-fluid">
            	<div class="row">
                	<div class="col-md-8 col-sm-8 col-xs-12">
        				<div class="logo">
            				<a href="#"><img src="img/logo_03.png" alt="image descraption"></a>
            			</div>
                	</div>
                    <div class="col-md-4 col-sm-4 col-xs-12">
                    	<a href="#"><span class="food"><span>Foot Pandits</span></span></a>
                    	<a href="<%= signin_path %>"><span class="login"><span>Login</span></span></a>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
        	<div class="row" >
            	<div class="col-md-12 col-sm-12 col-xs-12">
                	<div class="main-s">
                        <div class="main-section">
                        	<h1>Welcome</h1>
                            <span>to the world</span><br><br><br>
                            <p>of foods</p>
                        	<img src="img/icon18.png">
                            <div class="main-section-update">
                            	<p>Select few of your favourite restaurent to stay</p>
                                <h2>updated about them</h2>
                                <div class="cup">
                                	<img src="img/icon20.png">
                                </div>
                                <div class="stoberry">
                                	<img src="img/img12.png">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="main-leftpan">
                        <img src="img/icon16.png" alt="image descrp">
                    </div>
                    <div class="main-rightpan">
                    	<img src="img/icon19.png" alt="image descrp">
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid" style="margin-top: 250px; background-color: #ffffff;">
    	<article class="article">
        	<div class="row">
            	<div class="col-md-12">
                    <a href="#"><img src="img/img05.png" alt="image descrp"></a>
                    <a href="#"><img src="img/img06.png" alt="image descrp"></a>
                    <a href="#"><img src="img/img07.png" alt="image descrp"></a>
                    <a href="#"><img src="img/img08.png" alt="image descrp"></a>
                </div>
        	</div>
        </article>
        <article class="article">
        	<div class="row">
            	<div class="col-md-12">
                    <a href="#"><img src="img/img09.png" alt="image descrp"></a>
                    <a href="#"><img src="img/img11.png" alt="image descrp"></a>
                    <a href="#"><img src="img/img10.png" alt="image descrp"></a>
                    <a href="#"><img src="img/img09.png" alt="image descrp"></a>
                </div>
        	</div>
        </article>
    </div>
</div>

app/views/web/signin.html.erb
<link href="css/style.css" rel="stylesheet" type="text/css">
<link href="css/checkbox.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="css/normalize.css" />
<link rel="stylesheet" type="text/css" href="css/demo.css" />
<link rel="stylesheet" type="text/css" href="css/ns-default.css" />
<link rel="stylesheet" type="text/css" href="css/ns-style-bar.css" />

<style type="text/css">
#customBtn {
  width: inherit;
  border-radius: 21px;
  margin-top: -40px;
}
#customBtn:hover {
  cursor: pointer;
  opacity:0.7;
}

</style>

<div id="wrapper">
	<header class="header" role="main">
    	<img src="img/img01.jpg" alt="image descraption">
        <nav class="nav-top">
        	<div class="container-fluid">
            	<div class="row">
                	<div class="col-md-8 col-sm-8 col-xs-12">
        				<div class="logo">
            				<a href="#"><img src="img/logo_03.png" alt="image descraption"></a>
            			</div>
                	</div>
                    <div class="col-md-4 col-sm-4 col-xs-12">
                    	<a href="#"><span class="food"><span>Foot Pandits</span></span></a>
                    	<a href="<%= signin_path %>"><span class="login"><span>Login</span></span></a>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container">
        	<div class="l-main">
            	<div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="l-main-left">
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <input id="signin-username" type="text" class="form-control" placeholder="Username">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <a href="javascript:;" class="forget-password">Forget username?</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <input id="signin-password" type="password" class="form-control" placeholder="Password">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <a href="javascript:;" class="forget-password">Forget password?</a>
                                </div>
                            </div>
                            <div class="row">
                            	<div class="col-md-12 col-sm-12 col-xm-12">	
                                    <ul class="list">
                                        <li>
                                        <input tabindex="13" type="checkbox" id="flat-checkbox-1">
                                        <label for="flat-checkbox-1"></label>
                                        </li>
                                        <br><br>
                                        <a href="javascript:;" class="forget-password">Remember me</a>
                                    </ul>
                                </div>
                            </div>
                            <div class="row">
                            	<div class="col-md-12">
                                	<input type="button" class="form-control-sign-in" onclick="loginsubmit();" placeholder="" value="Sign In">
                                </div>
                            </div>
                            <div class="row">
                            	<div class="col-md-12">
                                	<div class="social-icon">
                                    	<p>Or login with</p>
                                    	<a href="users/auth/twitter"><img src="img/icon10.png" alt="image desrcp"></a>
                                        <a href="users/auth/facebook" id='sign_in'><img src="img/icon09.png" alt="image desrcp"></a>
                                        <a href="users/auth/google_oauth2"><img src="img/icon08.png" alt="image desrcp"></a>
                                        <!-- <div id="gSignInWrapper">
                                            <div id="customBtn" class="customGPlusSignIn">
                                              <img src="img/icon08.png" alt="image desrcp">
                                            </div>
                                        </div> -->
                                    </div>
                                    <!-- <div id="custom_signin_button"></div> -->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                    	<div class="account">
                        	<h1>Creat Account</h1>
                            <p>is simply dummy text of the printing and<br>typesetting industry. Lorem Ipsum has been<br>the industry's standard dummy text ever<br>since the</p>
                            <div class="row">
                            	<div class="col-md-8">
                                	<input type="button" onclick="location.href='<%= signup_path %>';" class="form-control-sign-up" placeholder="" value="Sign Up">
                                </div>
                                <div class="col-md-4">
                                	<img src="img/icon11.png" alt="image descrp">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
</div>

<script>
$(document).ready(function(){
  $('input').iCheck({
    checkboxClass: 'icheckbox_flat-green',
  });
});
</script>